algoritmo "variaveis"
var
    nome: caractere
    idade: inteiro
    altura: real
    casado: logico
    vetUni: vetor[0..4] de real
    vetBid: vetor[0..1,0..4] de real
    
inicio
      nome <- "Iury Chagas"
      idade <- 23
      altura <- 1.70
      casado <- falso
      vetUni [2] <- 17
      vetUni [3] <- 18
      vetBid [0,2] <- 24
      vetBid [0,4] <- 23
      vetBid [1,0] <- 22
      vetBid [1,1] <- 21
fimalgoritmo
